version: "3.2"
services:
  web:
    image: php:latest
    ports:
    - "8001:80"
    depends_on:
    - mysql
  mysql:
    image: mysql:latest
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
volumes:
  db_data: {}